# Generated by Django 3.0.7 on 2020-08-13 14:20

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('info', models.TextField(blank=True)),
                ('status', models.BooleanField(default=False)),
                ('date', models.DateField(default=datetime.datetime(2020, 8, 13, 14, 20, 10, 752550, tzinfo=utc))),
                ('time_start', models.DateTimeField(blank=True)),
                ('time_end', models.DateTimeField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
