# Generated by Django 3.0.7 on 2020-08-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0002_auto_20200813_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_end',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='time_start',
            field=models.DateField(blank=True),
        ),
    ]
