# Generated by Django 3.0.7 on 2020-08-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plannerapp', '0005_auto_20200814_1039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='time_end',
            field=models.TimeField(blank=True, default=None),
        ),
    ]
